volumes:
  laravel11-db-store:

services:
  app:
    container_name: laravel11-app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/workspace
    depends_on:
     - db
    env_file:
      - ./.env

  web:
    container_name: laravel11-web
    build: ./docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./:/workspace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    container_name: laravel11-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PUBLISHED_PORT:-3306}:3306"
    volumes:
      - laravel11-db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-dbpass}
      - MYSQL_DATABASE=${DB_DATABASE:-php_nginx_mysql}
      - MYSQL_USER=${DB_USERNAME:-dbuser}
      - MYSQL_PASSWORD=${DB_PASSWORD:-dbpass}
      - TZ=Asia/Tokyo
