version: '3'
services:
  mysql80:
    image: mysql:8.0
    ports:
      - "13380:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: testdb
    volumes:
      - ./db:/var/lib/mysql
      - ./log:/log
      - ./my.cnf:/etc/mysql/conf.d/my.cnf